In [67]:
import random
import pandas as pd
import numpy as np

import scipy.sparse as sparse
from scipy.sparse.linalg import spsolve
from sklearn.preprocessing import MinMaxScaler

In [68]:
Q=np.array([[1,2,3],[4,5,6], [7,8,9]])

In [69]:
Q

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
Q.shape

(3, 3)

In [71]:
W = Q>0.5
W[W == True] = 1
W[W == False] = 0
# To be consistent with our Q matrix
#W = W.astype(np.float64, copy=False)

In [72]:
lambda_ = 0.1
n_factors = 1
m, n = Q.shape
n_iterations = 3

In [73]:
m

3

In [74]:
n

3

In [75]:
X = 5 * np.random.rand(m, n_factors) 
#Y = 5 * np.random.rand(n_factors, n)
Y=np.array([[5,5,5]])

In [76]:
Y

array([[5, 5, 5]])

In [77]:
X

array([[1.66499468],
       [0.14776769],
       [4.69715168]])

In [78]:
def get_error(Q, X, Y, W):
    return np.sum((W * (Q - np.dot(X, Y)))**2)

In [79]:
errors = []
for ii in range(n_iterations):
    X = np.linalg.solve(np.dot(Y, Y.T) + lambda_ * np.eye(n_factors), 
                        np.dot(Y, Q.T)).T
    Y = np.linalg.solve(np.dot(X.T, X) + lambda_ * np.eye(n_factors),
                        np.dot(X.T, Q))
    if ii % 100 == 0:
        print('{}th iteration is completed'.format(ii))
    errors.append(get_error(Q, X, Y, W))
Q_hat = np.dot(X, Y)
print('Error '.format(get_error(Q, X, Y, W)))

0th iteration is completed
Error of rated movies: 1.302867333053929


In [80]:
X

array([[0.43464146],
       [1.05321114],
       [1.67178083]])